[[language]]
name = "markdown"
language-servers = ["marksman", "mdpls"]

[language-server.mdpls]
command = "/home/keyzer/.cargo/bin/mdpls"
config = { markdown.preview.auto = true, markdown.preview.codeTheme = "github", markdown.preview.browser = "cromite"}
